<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [1]:
import numpy as np
def sma(a:np.array,window_len:int)->np.array:
    """sma(a,n)
        Entrega una lista la cual contiene la media movil simple de los n datos anteriores
        Parametros:
        a:np.array 
            Vector que contiene los elementos que se van a promediar
        n:int 
            Ventana del promedio
        Returns
        np.array 
            Vector que contiene los promedios"""
    sma=np.zeros(len(a)-1)                                                            #crea un arreglo de largo igual al largo del arreglo a menos 1
    for i in range(window_len,len(a)):                                                #se itera desde n hasta el largo del arreglo menos 1
        if i==window_len:                                                             #si es la primera iteracion
            sma[0]=np.cumsum(a)[i-1]/window_len                                       #entonces se promedia usualmente
        sma[i-window_len+1]=(np.cumsum(a)[i]-np.cumsum(a)[i-window_len])/window_len   #se promedian los ultimos n numeros
    return sma                                                                        #se retorna la lista con los promedios

    

In [291]:
# ejemplo 01
a = [1,2,3,4,5]
sma(a,2)

array([1.5, 2.5, 3.5, 4.5])

In [287]:
# ejemplo 02
a = [5,3,8,10,2,1,5,1,0,2]
sma(a,2)

array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [260]:
import numpy as np
def strides(a:np.array,n:int,p:int)->np.array:
    """strides(a,n,p)
        Entrega una matriz con los valores del arreglo desfasados en p terminos por n^2 filas
        Parametros:
        a:np.array 
            Vector que se ocupara para construir la matriz
        n:int 
            Numero de columnas que tendra la matriz
        p:int 
            Natural que indica el desfase que tengra el Arreglo a en la matriz
        Returns
        np.array 
            Matriz que tendra los valores del arreglo desfasados en p terminos"""
    if p>=n:
        return "El valor de p debe ser menor que el numero de columas"
    dimension_filas=p**2
    strides=np.array(np.zeros((dimension_filas,n)))                 #se define la matriz con las dimensiones necesarias
    cont=0                                                          #se define un contador
    for i in range(0,dimension_filas):                              #se itera sobre la dimension de las filas
        for j in range(0,n):                                        #se itera sobre la dimension de las columnas
            if i==0:                                                #si es la primera fila 
                strides[0,j]=a[j]                                   #entonces se deja igual el arreglo
                cont+=1                                             #se incrementa el contador
            elif (cont-i*p)>=(len(a)):                              #si el indice se pasa del largo del arreglo
                strides[i,j]=0                                      #escribir 0
                cont+=1                   
                return strides                                      #se retorna la matriz
            else:                                                   #sino
                strides[i,j]=a[cont-i*p]                            #se agrega el arreglo con un desfase de p terminos 
                cont+=1                                             #se incrementa el contador
    return strides

In [288]:
# ejemplo 01
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
strides(a,4,2)

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.],
       [ 7.,  8.,  9., 10.]])

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [283]:
import numpy as np
def es_cuadrada_numeros_consecutivos(A:np.array)->bool:
    """es_cuadrada_numeros_consecutivos
        Verifica si la matriz es cuadrada y tambien verifica si los numeros que contiene son consecutivos
        Parametros:
        A:np.array 
            Matriz a verificar
        Returns
        bool 
            True si cumple, False si no"""
    dim_filas=len(A[:,1])                                            #se define la dimension de las filas
    dim_columnas=len(A[1,:])                                         #se define la dimension de las columnas
    if dim_filas==dim_columnas:                                      #si es cuadrada
        dim=len(A)                                                   #se define la dimension de la matriz
        lista_numeros_consecutivos_A=[]                              #se crea una lista vacia que tendra los numeros consecutivos
        for k in range(1,dim**2+1):                                  #se itera sobre la dimension al cuadrado de la matriz
            for i in range(0,dim):                                   #se itera sobre la dimension de las filas
                for j in range(0,dim):                               #se itera sobre la dimension de las columnas
                    if A[i,j]==k:                                    #si algun elemento de la matriz es el numero k 
                        lista_numeros_consecutivos_A.append(A[i,j])  #entonces se agrega a la lista de numeros consecutivos
        if len(lista_numeros_consecutivos_A)==dim**2:                #si la lista tiene todos los numeros consecutivos
            return True                                              #retorna True
        else:
            return False                                             #sino False
    else:                                                            #sino es cuadrada retorna False
        return False
def es_cuadrado_magico(A:np.array)->bool:
    """es_cuadrado_magico(A)
        Verifica si la matriz A es cuadrado magico
        Parametros:
        A:np.array 
            Matriz a verificar
        Returns
        bool
            True si es cuadrado magico, False si no"""
    if es_cuadrada_numeros_consecutivos(A)==True:          #pregunta si la matriz es cuadrada y tiene numeros consecutivos
        suma_filas=[]                                      #se crea una lista vacia que tendra la suma de las filas
        suma_columnas=[]                                   #se crea una lista vacia que tendra la suma de las columnas
        suma_diagonales=[]                                 #se crea una lista vacia que tendra la suma de las diagonales
        elementos_diagonal_1=[]                            #se crea una lista vacia que tendra elementos de la diagonal 1
        elementos_diagonal_2=[]                            #se crea una lista vacia que tendra elementos de la diagonal 2
        dim=len(A)                                         #es la dimension de la matriz
        for j in range(0,dim):                             #se itera sobre las filas
            suma_filas.append(sum(A[:,j]))                 #se agrega la suma de la iesima fila
        for i in range(0,dim):                             #se itera sobre las columnas
            suma_columnas.append(sum(A[i,:]))              #se agrega la suma de la jesima columna
        for m in range(0,dim):                             #se itera sobre la diagonal
            elementos_diagonal_1.append(A[m,m])            #se agregan los elementos de la diagonal 1
            elementos_diagonal_2.append(A[m,dim-1-m])      #se agregan los elementos de la diagonal 2
        suma_diagonales.append(sum(elementos_diagonal_1))  #se agrega la suma de los elementos de la diagonal 1
        suma_diagonales.append(sum(elementos_diagonal_2))  #se agrega la suma de los elementos de la diagonal 2
        if suma_filas==suma_columnas:                      #si las listas de las sumas de las filas y columnas son iguales
            if suma_diagonales[0]==suma_diagonales[1]:     #si la suma de ambas diagonales es igual
                if suma_filas[0]==suma_diagonales[0]:      #si la suma de las filas y columnas es igual a la de las diagonales
                    return True                            #retorna True
                else:
                    return False                           #sino False
        else:
            return False
                

In [289]:
# ejemplo 01
A=np.array([[4,9,2],[3,5,7],[8,1,6]])
es_cuadrado_magico(A)

True

In [290]:
#ejemplo 02
B = np.array([[4,2,9],[3,5,7],[8,1,6]])
es_cuadrado_magico(B)

False